// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDB-DIUlJMoxlsfjCp9NS_6hEQ0UnLroo',
    appId: '1:629664648785:web:b6540eea391c2620e7b270',
    messagingSenderId: '629664648785',
    projectId: 'brew-today',
    authDomain: 'brew-today.firebaseapp.com',
    storageBucket: 'brew-today.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUGYrfRHxeNv-8A9ZbGW8hiuA6TM5OR8c',
    appId: '1:629664648785:android:4b06a644af0ac26ee7b270',
    messagingSenderId: '629664648785',
    projectId: 'brew-today',
    storageBucket: 'brew-today.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcWUjAEny9vIBvIBz0joDYeAoTDQrTcGw',
    appId: '1:629664648785:ios:56d68dcb6e516375e7b270',
    messagingSenderId: '629664648785',
    projectId: 'brew-today',
    storageBucket: 'brew-today.appspot.com',
    iosClientId: '629664648785-6lpsad3icg1nhhr5v5s0iajhsd0ea6ks.apps.googleusercontent.com',
    iosBundleId: 'com.example.brewToday',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcWUjAEny9vIBvIBz0joDYeAoTDQrTcGw',
    appId: '1:629664648785:ios:56d68dcb6e516375e7b270',
    messagingSenderId: '629664648785',
    projectId: 'brew-today',
    storageBucket: 'brew-today.appspot.com',
    iosClientId: '629664648785-6lpsad3icg1nhhr5v5s0iajhsd0ea6ks.apps.googleusercontent.com',
    iosBundleId: 'com.example.brewToday',
  );
}
