// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqng_g-nzFZqxkLLgxQiLqDE2UwgjGuo0',
    appId: '1:913668285573:web:df5f90bc67777a68d875ec',
    messagingSenderId: '913668285573',
    projectId: 'fit-quest-809e4',
    authDomain: 'fit-quest-809e4.firebaseapp.com',
    storageBucket: 'fit-quest-809e4.appspot.com',
    measurementId: 'G-PLDBG6MRML',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCeex464f96gquSS5yNueva5LJBR6EYSU',
    appId: '1:913668285573:android:a60c58be872652bfd875ec',
    messagingSenderId: '913668285573',
    projectId: 'fit-quest-809e4',
    storageBucket: 'fit-quest-809e4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIH7oraWKPVuLQMSVT9nNScJSp86MtHcw',
    appId: '1:913668285573:ios:8ddb085279fb8e51d875ec',
    messagingSenderId: '913668285573',
    projectId: 'fit-quest-809e4',
    storageBucket: 'fit-quest-809e4.appspot.com',
    iosClientId: '913668285573-j776s2he1uv4uhh8ltnmpg8ngmaalj09.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitQuest',
  );
}
